In [1]:
import os

import pandas as pd
import autonormalize as an
from autonormalize import normalize

In [2]:
df = pd.read_csv(os.path.join(os.getcwd(), 'autonormalize/examples/example_make_index'))
df = df.drop_duplicates()

In [3]:
deps = an.find_dependencies(df)

100%|██████████| 6/6 [00:00<00:00, 22.93it/s]

In [4]:
print(deps)

 --> A
 --> B
 --> C
 {A,B}  --> D
 {A,B}  --> E
 --> F

In [7]:
depdf = normalize.DepDF(deps, df, ['A','B', 'C', 'F'])
normalize.normalize_dataframe(depdf)

In [8]:
normalize.make_indexes(depdf)

In [9]:
dfs = depdf.return_dfs()

In [10]:
df

        A  B   C      D   E    F
0       8  2  19   True  10  304
1       7  1  13  False   8   91
2      13  1   4  False  14   52
3       3  2  14   True   5   84
4      16  2   8  False  18  256
5      13  2   9   True  15  234
6       6  3   8   True   9  144
7       3  1  -9  False   4  -27
8      12  1  14  False  13  168
9      11  1   4  False  12   44
10      4  0  -7  False   4    0
11     17  0   7  False  17    0
12     18  0  -6  False  18    0
13      0  0   6  False   0    0
14      6  3   9   True   9  162
15      4  0  10  False   4    0
16      4  2   8   True   6   64
17      1  1   9  False   2    9
18     14  3  -3   True  17 -126
19     14  3   6   True  17  252
20      2  2   3   True   4   12
21     13  2  10   True  15  260
22      2  3  13   True   5   78
23     15  1  11  False  16  165
24      0  0   5  False   0    0
25      7  2  -5   True   9  -70
26     24  0   7  False  24    0
27      1  0  16  False   1    0
28      4  0 -10  False   4    0
29     20  0   2  False  20    0
...    .. ..  ..    ...  ..  ...
15136  18  1  -9  False  19 -162
15399  17  2   7  False  19  238
15465   2  1  18  False   3   36
15480  11  2  12   True  13  264
15603  21  1  10  False  22  210
15877   2  3  14   True   5   84
16091  17  3  -1  False  20  -51
16215  21  2  18  False  23  756
16449  24  0   1  False  24    0
16472  23  1  18  False  24  414
16510  10  0  10  False  10    0
16651  23  3   3  False  26  207
16706   3  0  -5  False   3    0
16918   3  0  16  False   3    0
17014   0  0  20  False   0    0
17070   3  2  15   True   5   90
17085  24  1 -10  False  25 -240
17245  16  0  -4  False  16    0
17264  23  0  -3  False  23    0
17316   4  2  13   True   6  104
17340   9  1  -4  False  10  -36
18149   6  2  -3   True   8  -36
18559  15  0   2  False  15    0
18560  13  0  11  False  13    0
18593  25  1  -8  False  26 -200
18615  18  0   0  False  18    0
22962  16  3   3  False  19  144
24458  11  0  12  False  11    0
25274   1  2  -9   True   3  -18
27925  10  3   6   True  13  180

[3224 rows x 6 columns]

In [11]:
dfs[0]

       C_A_B_F   C    F  A_B
0            0  19  304   34
1            1  13   91   29
2            2   4   52   53
3            3  14   84   14
4            4   8  256   66
5            5   9  234   54
6            6   8  144   27
7            7  -9  -27   13
8            8  14  168   49
9            9   4   44   45
10          10  -7    0   16
11          11   7    0   68
12          12  -6    0   72
13          13   6    0    0
14          14   9  162   27
15          15  10    0   16
16          16   8   64   18
17          17   9    9    5
18          18  -3 -126   59
19          19   6  252   59
20          20   3   12   10
21          21  10  260   54
22          22  13   78   11
23          23  11  165   61
24          24   5    0    0
25          25  -5  -70   30
26          26   7    0   96
27          27  16    0    4
28          28 -10    0   16
29          29   2    0   80
...        ...  ..  ...  ...
15136     3194  -9 -162   73
15399     3195   7  238   70
15465     3196  18   36    9
15480     3197  12  264   46
15603     3198  10  210   85
15877     3199  14   84   11
16091     3200  -1  -51   71
16215     3201  18  756   86
16449     3202   1    0   96
16472     3203  18  414   93
16510     3204  10    0   40
16651     3205   3  207   95
16706     3206  -5    0   12
16918     3207  16    0   12
17014     3208  20    0    0
17070     3209  15   90   14
17085     3210 -10 -240   97
17245     3211  -4    0   64
17264     3212  -3    0   92
17316     3213  13  104   18
17340     3214  -4  -36   37
18149     3215  -3  -36   26
18559     3216   2    0   60
18560     3217  11    0   52
18593     3218  -8 -200  101
18615     3219   0    0   72
22962     3220   3  144   67
24458     3221  12    0   44
25274     3222  -9  -18    6
27925     3223   6  180   43

[3224 rows x 4 columns]

In [9]:
dfs[1]

     A_B   A  B      D   E
0      0   0  0  False   0
1      1   0  1  False   1
2      2   0  2   True   2
3      3   0  3   True   3
4      4   1  0  False   1
5      5   1  1  False   2
6      6   1  2   True   3
7      7   1  3   True   4
8      8   2  0  False   2
9      9   2  1  False   3
10    10   2  2   True   4
11    11   2  3   True   5
12    12   3  0  False   3
13    13   3  1  False   4
14    14   3  2   True   5
15    15   3  3   True   6
16    16   4  0  False   4
17    17   4  1  False   5
18    18   4  2   True   6
19    19   4  3   True   7
20    20   5  0  False   5
21    21   5  1  False   6
22    22   5  2   True   7
23    23   5  3   True   8
24    24   6  0  False   6
25    25   6  1  False   7
26    26   6  2   True   8
27    27   6  3   True   9
28    28   7  0  False   7
29    29   7  1  False   8
..   ...  .. ..    ...  ..
74    74  18  2  False  20
75    75  18  3  False  21
76    76  19  0  False  19
77    77  19  1  False  20
78    78  19  2  False  21
79    79  19  3  False  22
80    80  20  0  False  20
81    81  20  1  False  21
82    82  20  2  False  22
83    83  20  3  False  23
84    84  21  0  False  21
85    85  21  1  False  22
86    86  21  2  False  23
87    87  21  3  False  24
88    88  22  0  False  22
89    89  22  1  False  23
90    90  22  2  False  24
91    91  22  3  False  25
92    92  23  0  False  23
93    93  23  1  False  24
94    94  23  2  False  25
95    95  23  3  False  26
96    96  24  0  False  24
97    97  24  1  False  25
98    98  24  2  False  26
99    99  24  3  False  27
100  100  25  0  False  25
101  101  25  1  False  26
102  102  25  2  False  27
103  103  25  3  False  28

[104 rows x 5 columns]

In [12]:
entityset = an.auto_entityset(df, name="example")

100%|██████████| 6/6 [00:00<00:00, 19.05it/s]

In [13]:
entityset

Entityset: example
  Entities:
    C_A_B_F [Rows: 3224, Columns: 4]
    A_B [Rows: 104, Columns: 5]
  Relationships:
    C_A_B_F.A_B -> A_B.A_B