In [1]:
import pandas as pd
from normalize import drop_primary_dups
from classes import Dependencies

In [2]:
df_dic = { "city": ['honolulu', 'boston', 'honolulu', 'dallas', 'seattle', 'honolulu', 'boston', 'honolulu', 'seattle', 'boston'], 
          "state": ['HI', 'MA', 'HI', 'TX', 'WA', 'AL', 'MA', 'HI', 'WA', 'NA'],
          "is_liberal": [True, True, True, False, True, True, True, True, True, False]}

In [3]:
df = pd.DataFrame(df_dic)
dep_dic = {"city": [], "state": [["city"]], "is_liberal": [["city"]]}
deps = Dependencies(dep_dic)

In [4]:
new_df = drop_primary_dups(df, deps)

In [5]:
new_df

       city state  is_liberal
0    boston    MA        True
1    dallas    TX       False
2  honolulu    HI        True
3   seattle    WA        True

In [6]:
import os
import user_interaction
import normalize
import pandas as pd

In [29]:
pollution_df = pd.read_csv(os.path.join(os.getcwd(), 'downloads/pollution.csv'))
pollution_df = pollution_df.drop(columns=pollution_df.columns[9:])
pollution_df_small = pollution_df.drop(range(10000000, 1746661))
pollution_df_small = pollution_df_small.drop(columns=['Date Local'])
pollution_df_small = pollution_df_small.drop_duplicates()

In [30]:
deps = user_interaction.find_dependencies(pollution_df_small, 0.95, 0.85)

100%|██████████| 8/8 [00:36<00:00,  4.51s/it]

In [31]:
deps.serialize()

{'Unnamed: 0': [],
 'State Code': [['State'],
  ['Site Num', 'City'],
  ['County'],
  ['Site Num', 'County Code'],
  ['Address'],
  ['City', 'County Code']],
 'County Code': [['Site Num', 'City'],
  ['County'],
  ['Address'],
  ['City', 'State Code'],
  ['City', 'State']],
 'Site Num': [['Address']],
 'Address': [['Site Num', 'County Code'],
  ['Site Num', 'City'],
  ['Site Num', 'County']],
 'State': [['Site Num', 'City'],
  ['County'],
  ['Site Num', 'County Code'],
  ['Address'],
  ['City', 'County Code'],
  ['State Code']],
 'County': [['Site Num', 'City'],
  ['State', 'County Code'],
  ['Address'],
  ['Site Num', 'County Code'],
  ['City', 'County Code'],
  ['City', 'State Code'],
  ['City', 'State'],
  ['State Code', 'County Code']],
 'City': [['Site Num', 'County Code'], ['Address'], ['Site Num', 'County']]}

In [9]:
print(deps)

 --> Unnamed: 0
 {Unnamed: 0,County Code}  {State}  {Site Num,City}  {County}  {Address}  {Site Num,County Code}  {City,County Code}  --> State Code
 {Site Num,City}  {County}  {Address}  {City,State Code}  {City,State}  --> County Code
 {Address}  --> Site Num
 {Site Num,County Code}  {Site Num,City}  {Site Num,County}  --> Address
 {Unnamed: 0,County Code}  {Site Num,City}  {County}  {Site Num,County Code}  {Address}  {City,County Code}  {State Code}  --> State
 {Unnamed: 0,County Code}  {Site Num,City}  {State,County Code}  {Address}  {Site Num,County Code}  {City,County Code}  {City,State Code}  {City,State}  {State Code,County Code}  --> County
 {Site Num,County Code}  {Address}  {Site Num,County}  --> City

In [32]:
grps = user_interaction.normalize_dependencies(deps)

In [11]:
print(grps)

[<classes.Dependencies object at 0x112ac1cc0>, <classes.Dependencies object at 0x113ef37b8>, <classes.Dependencies object at 0x113ef3390>]

In [16]:
new_dfs = user_interaction.split_dataframe(pollution_df_small, grps)

In [23]:
print(deps)

 --> Unnamed: 0
 {State}  --> State Code
 {County}  --> County Code
 {Address}  --> Site Num
 {Site Num,City}  {Site Num,County}  --> Address
 {County}  --> State
 {Site Num,City}  {Address}  --> County
 {Address}  {Site Num,County}  --> City

In [19]:
new_dfs[0]

,Unnamed: 0,Site Num,Address,County,City
0,87920,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
1,87921,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
2,87922,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
3,87923,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
4,87924,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
5,87925,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
6,87926,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
7,87927,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
8,87928,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
9,87929,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
10,87930,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
11,87931,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
12,87932,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
13,87933,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
14,87934,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
15,87935,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
16,87936,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
17,87937,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
18,87938,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
19,87939,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
20,87940,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
21,87941,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
22,87942,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
23,87943,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
24,87944,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
25,87945,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
26,87946,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
27,87947,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
28,87948,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
29,87949,1004,6100 ARLINGTON BLVD MONTG WARD,Fairfax,Seven Corners
...,...,...,...,...,...
261093,84108,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261094,84109,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261095,84110,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261096,84111,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261097,84112,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261098,84113,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261099,84114,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261100,84115,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261101,84116,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261102,84117,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261103,84118,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261104,84119,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261105,84120,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261106,84121,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261107,84122,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261108,84123,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261109,84124,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261110,84125,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261111,84126,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261112,84127,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261113,84128,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261114,84129,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261115,84130,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261116,84131,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261117,84132,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261118,84133,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261119,84134,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261120,84135,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261121,84136,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg
261122,84137,25,WASHINGTON & CAMBRIA STS. FREEMANSBURG,Northampton,Freemansburg

In [20]:
new_dfs[1]

    County Code                 State                County
0             1              Colorado                 Adams
1             1            California               Alameda
2           510              Virginia       Alexandria City
3             3          Pennsylvania             Allegheny
4             7          Pennsylvania                Beaver
5            11          Pennsylvania                 Berks
6            13          Pennsylvania                 Blair
7            19              Kentucky                  Boyd
8             5              New York                 Bronx
9            17          Pennsylvania                 Bucks
10           21          Pennsylvania               Cambria
11            7            New Jersey                Camden
12           21              Oklahoma              Cherokee
13            3                Nevada                 Clark
14           13            California          Contra Costa
15           31              Illinois                  Cook
16          113                 Texas                Dallas
17           59              Kentucky               Daviess
18            1  District Of Columbia  District of Columbia
19           33             Louisiana      East Baton Rouge
20          141                 Texas               El Paso
21           13            New Jersey                 Essex
22           59              Virginia               Fairfax
23           67              Kentucky               Fayette
24           67        North Carolina               Forsyth
25           19            California                Fresno
26          201                 Texas                Harris
27           75             Tennessee               Haywood
28          101              Kentucky             Henderson
29           11         New Hampshire          Hillsborough
..          ...                   ...                   ...
41           97               Indiana                Marion
42          145              Kentucky             McCracken
43          119        North Carolina           Mecklenburg
44          121             Tennessee                 Meigs
45           91          Pennsylvania            Montgomery
46           95          Pennsylvania           Northampton
47           59            California                Orange
48          115              Oklahoma                Ottawa
49          101          Pennsylvania          Philadelphia
50           19               Arizona                  Pima
51           81              New York                Queens
52           65            California             Riverside
53           67            California            Sacramento
54          163              Illinois           Saint Clair
55          189              Missouri           Saint Louis
56           71            California        San Bernardino
57           73            California             San Diego
58           75            California         San Francisco
59           83            California         Santa Barbara
60           87            California            Santa Cruz
61           95            California                Solano
62          510              Missouri        St. Louis City
63          103              New York               Suffolk
64          191                Kansas                Sumner
65          111            California               Ventura
66          125          Pennsylvania            Washington
67          163              Michigan                 Wayne
68          129          Pennsylvania          Westmoreland
69          209                Kansas             Wyandotte
70          133          Pennsylvania                  York

[71 rows x 3 columns]

In [21]:
new_dfs[2]

    State Code                 State
0            4               Arizona
1            6            California
2            8              Colorado
3           11  District Of Columbia
4           12               Florida
5           17              Illinois
6           18               Indiana
7           20                Kansas
8           21              Kentucky
9           22             Louisiana
10          25         Massachusetts
11          26              Michigan
12          29              Missouri
13          32                Nevada
14          33         New Hampshire
15          34            New Jersey
16          36              New York
17          37        North Carolina
18          40              Oklahoma
19          42          Pennsylvania
20          47             Tennessee
21          48                 Texas
22          51              Virginia